DashBoardDemo/Controllers/AdminDemoController.cs
using DashBoardDemo.Interface;
using DashBoardDemo.ModelDb;
using DashBoardDemo.Models;
using DashBoardDemo.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Castle.Core.Smtp;

namespace DashBoardDemo.Controllers
{

    [SessionActionFilter]
    public class AdminDemoController : Controller
    {
        private readonly ILogger<AdminDemoController> _logger;
        private readonly AppDbContext appDbContext;
        private readonly IAdminDemoService adminDemoService;
        private readonly IStatisticsService statisticsService;
       
        private readonly IPieChartService pieChartService;
        //string conStr = @"Data Source=.;Initial Catalog=DoctorAppdb;User ID=sa;Password=Abbacus007";

        public AdminDemoController(ILogger<AdminDemoController> logger, AppDbContext appDbContext, IAdminDemoService adminDemoService, IStatisticsService statisticsService,  IPieChartService pieChartService)
        {
            _logger = logger;
            this.appDbContext = appDbContext;
            this.adminDemoService = adminDemoService;
            this.statisticsService = statisticsService;
           
            this.pieChartService = pieChartService;
        }
        public IActionResult Index()
        {
            return View();
        }

       
      
        //THIS IS FOR DASHBOARD CARDS
        public IActionResult DashBoard()
        {
            var totalDoctors = statisticsService.GetTotalDoctors();
            var totalPatients = statisticsService.GetTotalPatients();
            var todaysPatients = statisticsService.GetTodaysPatients();
            var approved = statisticsService.ApprovedApp();
            var rejected = statisticsService.RejectApp();

            ViewBag.TotalDoctors = totalDoctors;
            ViewBag.TotalPatients = totalPatients;
            ViewBag.TodaysPatients = todaysPatients;
            ViewBag.Approved = approved;
            ViewBag.Rejected = rejected;

            return View();
        }

        //For the Piechart and Graph
        [HttpGet]
        public async Task<ActionResult<IEnumerable<TimeSlot_Patients>>> GetTimeSlotPatientsRecords()
        {
            var timeslotRecords = await pieChartService.GetTimeSlotRecords();
            return Ok(timeslotRecords);
        }

        //PATIENTS WORKS
        //VIEW FOR PATIENTLIST
        public IActionResult PatientList()
        {
           
            return View();
        }
        //used for DataTable for PAtients List
        public IActionResult GetPatientsList()
        {
            var data = appDbContext.Patients.OrderByDescending(x=>x.Id).ToList();
            return new JsonResult(data);
        }

        //  BELOW TWO FOR ONE IS FOR VIDE FIRST ONE SECOND IS FOR UPDATE PATIENTS TABLE DATA
        public IActionResult EditViewPatients()
        {
            return View();
        }
        //USED TO SHOW PATIENTS LIST IN THE TABLE
        [HttpGet]
        public async Task<JsonResult> GetPatientList()
        {
            var entitydata = await adminDemoService.GetAllData();

            return Json(entitydata);
        }
        //USED FOR PUT PATIENTS VALUES FROM THE PATINET VIEW TO THE EDIT FORM 
        [HttpGet]
        public async Task<JsonResult> GetPutaPatientData(int Id)
        {

            var empdata = await adminDemoService.GetByIdPatient(Id);
            return Json(empdata);
        }
        //UPDATE IN THE PATIENT VIEW 
        [HttpPost]
        public async Task<IActionResult> Submit(Patient add)
        {
            try
            {
                var updatedPatient = await adminDemoService.Update(add);
                return Json(updatedPatient);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        //DELETE FROM THE PATIENT VIEW, PATIENTS DATA
        [HttpPost]
        public async Task<JsonResult> DeleteData(int Id)
        {

            var empdata = await adminDemoService.Delete(Id);
            return Json(empdata);
        }
        
       //SEARCH IMPLEMENTATION IN THE PATINETS LIST
        [HttpPost]
        public async Task<IActionResult> Search( string PatientName)
        {
            var patient = await adminDemoService.FilterDataSearching( PatientName);
            return Json(patient);
        }




    
        //USED TO SHOW DOCTORS LIST VIEW IT IS

        public IActionResult DoctorMaster()
        {
            return View();
        }
       //Used for client side Doctor List
        public IActionResult GetDoctorList()
        {
            var data = appDbContext.Doctors.OrderByDescending(x=>x.Id).ToList();
            return new JsonResult(data);
           
        }

        //USED FOR TO SHOW DOCTORS DATA IN TABLE
        [HttpGet]
        public async Task<JsonResult> GetDoctorMaster()
        {
            var doctordata = await adminDemoService.GetAllDataDoctor();

            return Json(doctordata);
        }
        //For edit in DoctorMaster
        [HttpGet]
        public async Task<JsonResult> GetPutData(int Id)
        {

            var empdata = await adminDemoService.GetById(Id);
            return Json(empdata);
        }

        //For Add Doctors inside the Doctormaster table 
        public IActionResult Create()
        {
            return View();
        }
        //For Add Doctors inside the Doctormaster table 
        [HttpPost]
        public async Task<JsonResult> Register(Doctor std)
        {
            try
            {
                if (std.Id > 0)
                {


                    var entitydata = await adminDemoService.Update(std);

                    return Json(entitydata);

                }
                else
                {

                    var entitydata = await adminDemoService.Insert(std);

                    return Json(entitydata);
                }

                appDbContext.SaveChanges();
                return Json(true);
            }
            catch (Exception ex)
            {

                throw;
            }
        }






        //Below two methods used to show patient TimeSlot table
        public IActionResult PatientTimeSlot()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetTimeSlotPatients()
        {
            try
            {
                var timeSlotPatients = await adminDemoService.GetPatientsTimeSlot();
                return Json(timeSlotPatients);
            }
            catch (Exception ex)
            {
                // Handle the exception appropriately
                return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while retrieving data.");
            }
        }

        //WORK -> TO UPDATE ISAPPROVED COLUMN VALUE IN THE DATABASE TABLE TIMESLOT_PATIENTS AND SHOW IN TABLE APPROVED OR REJECTED
        [HttpPost]
        public async Task<IActionResult> UpdateApprovalStatus(int id, bool isApproved)
        {
            try
            {
                await adminDemoService.UpdateApprovalStatus(id, isApproved);
                return Ok();
            }
            catch (Exception ex)
            {
                // Handle the exception appropriately
                return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while updating the approval status.");
            }
        }

        


        
        [HttpGet]
        public async Task<JsonResult> GetAllDoctorNames()
        {
            try
            {
                var doctors = await adminDemoService.GetAllDoctors();

                if (doctors != null && doctors.Any())
                {
                    var doctorNames = doctors.Select(d => new
                    {
                        doctorId = d.Id,
                        doctorName = d.DoctorName
                    }).ToList();

                    return Json(new { success = true, doctorNames });
                }
                else
                {
                    return Json(new { success = false, message = "No doctors found." });
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        //For Showing Time slot of doctors
        public IActionResult TimeSlotDoc()
        {
            return View();
        }
       


        //For Add DoctorsTimeSlot inside the Doctormaster table 
        public IActionResult AddDoc()
        {
            return View();
        }


        //For Insert data into  TimeSlotDoctor  table
        [HttpPost]
        public async Task<JsonResult> SubmitData(View_DoctorTimeSlot data)
        {
            try
            {
                // Check if the doctor with the provided ID exists
                var doctorExists = await adminDemoService.DoctorExists(data.DoctorId);
                if (!doctorExists)
                {
                    return Json(new { success = false, message = "Invalid Doctor ID. Please select a valid doctor." });
                }

                // Perform the insertion
                var result = await adminDemoService.InsertSlot(data);
                if (result)
                {
                    return Json(new { success = true });
                }
                else
                {
                    return Json(new { success = false, message = "Failed to insert time slot." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "An error occurred while submitting data." });
            }
        }






        //To show TimeSlotDocor Data in Table

        [HttpGet]
        public async Task<IActionResult> GetTimeSlotDoctor()

DashBoardDemo/Controllers/DoctorController.cs
using DashBoardDemo.Interface;
using DashBoardDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace DashBoardDemo.Controllers
{
    [SessionActionFilter]
    public class DoctorController : Controller
    {
        private readonly ILogger<DoctorController> _logger;
        private readonly AppDbContext appDbContext;
        private readonly IDoctorsService doctorsService;
        private readonly IPatientDataService patientDataService;
        //string conStr = @"Data Source=.;Initial Catalog=FormData;User ID=sa;Password=Abbacus007";

        public DoctorController(ILogger<DoctorController> logger, AppDbContext appDbContext, IDoctorsService doctorsService, IPatientDataService patientDataService)
        {
            _logger = logger;
            this.appDbContext = appDbContext;
            this.doctorsService = doctorsService;
            this.patientDataService = patientDataService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DoctorList()
        {
            return View();
        }


        [HttpGet]
        public async Task<JsonResult> GetDoctors()
        {
            var doctordata = await doctorsService.GetAllDataDoctor();

            return Json(doctordata);
        }

        [HttpGet]
        public async Task<JsonResult> GetPutData(int Id)
        {

            var empdata = await doctorsService.GetById(Id);
            return Json(empdata);
        }


        //To put DoctorName in PatientView Form
        [HttpGet]
        public async Task<JsonResult> GetDoctorDetails(int Id)
        {
            try
            {
                var doctor = await doctorsService.GetById(Id);

                if (doctor != null)
                {
                    var doctorDetails = new
                    {
                        success = true,
                        doctorName = doctor.DoctorName,
                        
                    };

                    return Json(doctorDetails);
                }
                else
                {
                    return Json(new { success = false, message = "Doctor not found." });
                }
            }
            catch (Exception ex)
            {
                throw;
                
            }
        }

        

        //INSERT SLOT TIME OF DOCTORS ACCORDING TO THEIR ID IN THE PATIENTVIEW FORM
        [HttpGet]
        public IActionResult GetDoctorTimeSlots(int DoctorId, DateTime selectedDate)
        {
            try
            {
                // Validate if selectedDate is not a future date
                if (selectedDate.Date > DateTime.Today)
                {
                    return Json(new { success = false, message = "No slots available for the selected date." });
                }

                var timeSlots = doctorsService.GetDoctorTimeSlots(DoctorId,selectedDate);

                if (timeSlots != null && timeSlots.Any())
                {
                    return Json(new { success = true, timeSlots });
                }
                else
                {
                    return Json(new { success = false, message = "No slots available for the selected date." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        public IActionResult PatientDataView()
        {
            return View();
        }

        public IActionResult PatientDetails()
        {
            return View();
        }

        public IActionResult TimeSlotViewPatient()
        {
            return View();
        }


        //Session used for Sigle Patient Get into the Doctor Controller
        [HttpGet]
        public async Task<IActionResult> GetPatientData()
        {
            var userSessionJson = HttpContext.Session.GetString("UserSession");
            var userSession = JsonConvert.DeserializeObject<LoginSessionClass>(userSessionJson);
           


            var patientData = await patientDataService.GetAttendanceWithPatientDataAsync(userSession.UserId);
            return Json(patientData);
        }

        /*[HttpGet]
        public async Task<IActionResult> GetPatientData()
        {
            var userSessionJson = HttpContext.Session.GetString("UserSession");
            var userSession = JsonConvert.DeserializeObject<LoginSessionClass>(userSessionJson);

            var patientData = await patientDataService.GetAttendanceWithPatientDataAsync(userSession.UserId);

            // Create a list to store patient names
            var patientNames = new List<string>();

            // Retrieve the patient names from the patientData object and add them to the list
            foreach (var patient in patientData)
            {
                var patientName = patient.Name;
                patientNames.Add(patientName);
            }

            // Pass the patient names to the front-end using ViewData
            ViewData["PatientNames"] = patientNames;

            return Json(patientData);
        }*/



        [HttpGet]
        public async Task<IActionResult> GetPatientTimeSlotData()
        {
            var userSessionJson = HttpContext.Session.GetString("UserSession");
            var userSession = JsonConvert.DeserializeObject<LoginSessionClass>(userSessionJson);
            //var employeeData = JsonConvert.DeserializeObject<EmployeMasterForm>(userId);


            var patientData = await patientDataService.GetPatientTimeslotDataAsync(userSession.UserId, userSession.UserRole);
            return Json(patientData);
        }






    }
}

DashBoardDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DashBoardDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DashBoardDemo.styles.css" asp-append-version="true" />
    <link href="~/css/datatablecss/jquery.datatables.css" rel="stylesheet" />
    <link href="~/css/datatablecss/jquery.datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex flex-column flex-sm-row justify-content-between align-items-start align-items-sm-center">
                    <div class="mb-3 mb-sm-0">
                        <a class="navbar-brand fw-bold" asp-area="" asp-controller="" asp-action="">
                            <i class="fas fa-hospital me-2" style="font-size: 20px;"></i>
                            <span style="font-size: 18px;">Doctor Appointment System</span>
                        </a>

                        <div class="navbar-text ms-3">
                            <span id="welcomeMessage"></span>
                            <span id="dateTime"></span>
                        </div>
                    </div>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="AdminDemo" asp-action="Dashboard">
                                <i class="fas fa-chart-bar me-2"></i>Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="AdminDemo" asp-action="DoctorMaster">
                                <i class="fas fa-user-md me-2"></i>Doctor Master
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="AdminDemo" asp-action="PatientList">
                                <i class="fas fa-users me-2"></i>Patient List
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="AdminDemo" asp-action="PatientTimeSlot">
                                <i class="far fa-calendar-alt me-2"></i>Patient TimeSlot
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="AdminDemo" asp-action="TimeSlotDoc">
                                <i class="far fa-clock me-2"></i>Doctor TimeSlot
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark fw-bold" href="#" id="serverSideDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-database me-2"></i>Server Side Data
                            </a>
                            <div class="dropdown-menu" aria-labelledby="serverSideDropdown" data-bs-hover="true">
                                <a class="dropdown-item text-dark fw-bold" asp-area="" asp-controller="ServerSide" asp-action="ServerSideDoctorsList">Doctor List</a>
                                <a class="dropdown-item text-dark fw-bold" asp-area="" asp-controller="ServerSide" asp-action="ServerSidePatientsList">Patient List</a>
                                <a class="dropdown-item text-dark fw-bold" asp-area="" asp-controller="ServerSide" asp-action="ServerSidePatientTimeSlot">Patient TimeSlot</a>
                                <a class="dropdown-item text-dark fw-bold" asp-area="" asp-controller="ServerSide" asp-action="ServerSideDoctorsTimeSlot">Doctor TimeSlot</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="PatientLogin" asp-action="Logout" style="color: #7E22CE;">
                                <i class="fas fa-sign-out-alt me-2"></i>Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @*//For the Loading inage Html*@
            <div id="overlayfullscreenloader" class="overlayfullscreenloader" style="display:none">
                <span></span>
                <img id="imgFullScreenLoader" src="~/img/SKVI.gif">
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DashBoardDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/datatable/jquery.datatables.js"></script>
    <script src="~/datatable/jquery.datatables.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


 @*This is used for the dropdown slidedown for the server sie tables in the admin page*@
<script>
    //For the Loading inage Script
    $(document).ready(function () {
        $('.dropdown').hover(
            function () {
                $(this).addClass('show');
                $(this).find('.dropdown-menu').slideDown(300); 
            },
            function () {
                var dropdownMenu = $(this).find('.dropdown-menu');
                dropdownMenu.slideUp(300, function () { 
                    $(this).removeClass('show');
                });
                $(this).removeClass('show');
            }
        );
    });


</script>
<script>
    $(document).ajaxStart(function () {
        $(".overlayfullscreenloader").show();
    }).ajaxStop(function () {
        $(".overlayfullscreenloader").hide();

    }).ajaxError(function (ex) {

    });


    $(document).ready(function () {
        // Get the username from the ViewBag in your Razor view
        var username = '@ViewBag.UserName';

        // Function to update the clock and date
        function updateDateTime() {
            var currentDate = new Date();
            var formattedDate = currentDate.getDate() + " " + currentDate.toLocaleString('default', { month: 'long' }) + ", " + currentDate.getFullYear();
            var formattedTime = currentDate.toLocaleString('default', { hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: true });

            $("#dateTime").text(formattedDate + " " + formattedTime);
        }

        // Function to display the welcome message
        function displayWelcomeMessage(username) {
            $("#welcomeMessage").text("Welcome, " + username);
        }

        // Call the functions initially
        updateDateTime();
        displayWelcomeMessage(username);

        // Update the clock every second
        setInterval(updateDateTime, 1000);
    });

</script>

DashBoardDemo/Views/Shared/_dashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DashBoardDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DashBoardDemo.styles.css" asp-append-version="true" />
    <link href="~/css/datatablecss/jquery.datatables.css" rel="stylesheet" />
    <link href="~/css/datatablecss/jquery.datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Doctor Appointment Systerm</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AdminDemo" asp-action="DashBoard">DashBoard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AdminDemo" asp-action="DoctorMaster">Doctor Master</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AdminDemo" asp-action="PatientList">Patient List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AdminDemo" asp-action="PatientTimeSlot">Patient_TimeSlot</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AdminDemo" asp-action="TimeSlotDoc">Doctors_TimeSlot</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="DoctorList">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

           